[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/api/health"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
healthcheckTimeout = 300

[env]
PORT = "8080"
PYTHONPATH = "/app"
